import type { Metadata } from "next";
import Link from "next/link";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

interface Props {
  frontmatter: {
    title: string;
    description?: string;
    favicon: string;
    thumbnail?: string;
  };
}

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex flex-col gap-4 items-center pt-12 pb-6 w-full [&>*]:px-6 [&>*]:max-w-[60rem] [&>astro-island>*]:px-6 [&>astro-island>*]:max-w-[60rem] text-zinc-900 bg-zinc-50 dark:text-zinc-50 dark:bg-zinc-900">
        {children}
        <footer className="m-auto mt-10">
          <p
            className="text-zinc-500 dark:text-zinc-400 text-sm [&_a]:text-blue-500 dark:[&_a]:text-blue-300"
          >
            This page was built using <Link
              href="https://github.com/RomanHauksson/academic-project-astro-template">
              Roman Hauksson's academic project page template
            </Link>
            , which was adapted from <Link
              href="https://github.com/eliahuhorwitz/Academic-project-page-template">
              Eliahu Horwitz's template
            </Link>
            , which was adapted from <Link href="https://nerfies.github.io/">
              Keunhong Park's project page for <i>Nerfies</i></Link>
            . It is licensed under a <Link href="http://creativecommons.org/licenses/by-sa/4.0/">
              Creative Commons Attribution-ShareAlike 4.0 International License</Link>.
          </p>
        </footer>
      </body>
    </html >
  );
}
