subject: "1001"

data:
  class_name: becominglit.data.bl_dataset.BecomingLitDataset
  subject: ${subject}
  sequences_subset: ["EXP-2", "EMOTIONS", "SEN-1", "SEN-2", "SEN-3"]
  downscale_factor: 2
  black_level_subtraction: 4.0
  fully_lit_only: false
  apply_alpha: true
  length_unit: "mm"

val_data:
  class_name: becominglit.data.bl_dataset.BecomingLitDataset
  subject: ${subject}
  sequences_subset: ["FREE"]
  downscale_factor: ${data.downscale_factor}
  black_level_subtraction: ${data.black_level_subtraction}
  fully_lit_only: ${data.fully_lit_only}
  apply_alpha: ${data.apply_alpha}
  length_unit: ${data.length_unit}
  cameras_subset:
    - "222200037"

dataloader:
  batch_size: 4
  num_workers: 8
  pin_memory: True
  persistent_workers: False
  shuffle: True

model_name: becominglit_release

model:
  class_name: becominglit.models.becominglit.BecomingLitModel
  diff_sh_deg: 6
  flame_config:
    shape_params: 300
    expr_params: 100

lr: 5e-4
optimizer:
  class_name: torch.optim.Adam
  per_module:
    geo_mod:
      lr: ${lr}
    spec_mod:
      lr: ${lr}
    expr_enc:
      lr: ${lr}
    view_enc:
      lr: ${lr}
    bsdf_mod:
      lr: ${lr}
    means:
      lr: 0.01
    albedo:
      lr: 0.002
    roughness:
      lr: 0.001

loss:
  class_name: becominglit.criterion.ModularLoss
  losses:
    rgb_l1:
      weight: 0.8
    rgb_ssim:
      weight: 0.2
    l2_reg:
      loss_fn: "l2_reg"
      key: normal_offsets
      schedule:
        class_name: becominglit.criterion.MonotonicWeightSchedule
        start: 0
        end: 100_000
        init_value: 1.0
        target_value: 0.0
    scale_bounds:
      loss_fn: bound_primscale_rgca
      weight: 1e-2
      min_scale: 0.1
      max_scale: 20.0
    negcolor:
      loss_fn: "negcolor"
      weight: 1e-1
    alpha_loss:
      loss_fn: "rgb_l2"
      weight: 1e-2
      src_key: "alpha"
      tgt_key: "alpha"

train:
  run_id: "debug" # NOTE: Override this from the cmd line with a unique id
  tag: ${model_name}.${subject}
  log_dir: null # Set from env variable
  run_dir: ${.log_dir}/${.tag}/${.run_id}
  ckpt_dir: ${.run_dir}/checkpoints

  n_max_iters: 250_000
  n_warmup_iters: 1_000
  log_every_n_steps: 100
  summary_every_n_steps: 5_000
  ckpt_every_n_steps: 50_000
  validate_every_n_steps: 50_000

summary:
  class_name: becominglit.models.becominglit.BecomingLitSummary
